---
title: "NTUSC"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(showtext)
showtext_auto()
font_add("jh", "msjh.ttc")
```

### **What is NTUSC?**

NTUSC是台大學代會的簡稱，其全名為 National Taiwan University Student Congress(國立臺灣大學學生會學生代表大會)，是台大學生自治的立法機關，由全體學生選舉所組成，和代表行政的學生會以及代表司法的學生法院形成三權互相制衡，其職責為代表學生爭取學生權利並監督學生會施政。

近來由於諸多議題如[中國新歌聲演唱會場地爭議](https://udn.com/news/story/6656/2732448)與[管中閔台大校長遴選爭議](https://www.upmedia.mg/news_info.php?SerialNo=40250)等有台大學代的參與，又因為媒體報導與網友關注，使得[台大學代低投票率](https://udn.com/news/story/11744/3136612)成為新聞報導的話題，也有[網友批評](https://udn.com/news/story/6656/3169818)，台大學代已經被特定政治力量所把持。


### **Why NTUSC?**

就我自己的經驗而言，身邊的同學們普遍不關心學生自治，無論是校內學生自治選舉(學生會會長與學生代表)，或者是選舉過後的施政與監督，因為生活重心不同，所以無暇或者無意願將目光放在此處。或許我們都曾經聽過 Plato 說過的名言: "One of the penalties for refusing to participate in politics is that you end up being governed by your inferiors." 然而，至少在台大裡面，學代的存在感實在太低，有沒有被糟糕的人統治，好像根本沒有太大的影響。

儘管存在感是如此的低，身旁仍有朋友或者同學前仆後繼的獻身於學生自治，並且每個人的目的與最終結果都不一樣。有積極爭取學生權益的、有想要改變環境但最終失敗的、有認真質詢以做好監督工作的、有學代缺席率高踞排行榜前三的、有投入選委工作的、有只為了增添履歷頭銜的，自然也有有成天訕笑學生自治，可是卻什麼事情都不做的，也有閉上嘴巴咬牙向前，踏踏實實的企圖做出改變的。

我對行政、立法、司法都沒有太大的興趣，既不喜歡參加活動，也不是很有動力監督學校，但還是想從適合的角度出發，貢獻自己的能力於學生自治。後來因緣際會接觸到 open data 的理念，當下便覺得或許能夠從開放資料/揭露資料開始，若同學們能夠以簡單的方式得知學生自治團體在做些什麼，對其有些基本的認識之後，也比較有可能產生興趣，進而深化參與。因此，我想要從開放資料的角度出發，讓台大學生可以看到關於台大學生代表的出席資料，再加上簡單的圖表與表格，對資料的全貌有更多認識。

### **What's the goal?**

學生自治有多種實踐方式，擔任學代是眾多方法之中非常好的一種，但也有其他很好的方式，參與系學會、院學會、性平會學生委員...，都可以為身旁的環境帶來改變。

對未曾接觸實際情況的同學來說，學代可能是無法產生影響的職位，也有可能是充滿改變可能的職位，然而在認識學代業務後，有人選擇背起責任將任期內的工作完成，也有人選擇缺席大半任期，因此，我想要透過揭露學代出席率，達成三個目標。在資訊充分揭露後，候選人能夠認識學代出席的生態，學代本身也更能夠和身旁其他同事比較，公眾也較能監督出席。

> * 影響候選人: 讓候選人能夠更好評估自身情況
> * 影響學代: 讓學代掌握自身出席情況
> * 影響公眾: 讓公眾更有意願關注學代

### **What's the output?**

我希望能夠影響候選人、學代、公眾，而要讓上述三者能夠更好的接近使用資料，具體手段如下:

> * 原始資料: 讓大家可以直接下載原始資料與code
> * 視覺化: 讓大家可以快速瞭解這份資料
> * 延伸性: 建立起固定工作流程(workflow), 並使其成為可重複性研究(reproducible research), 若有可能的話引入更多外部資料(data joining)